# Generated by Django 2.2.19 on 2021-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
