# Generated by Django 2.2.16 on 2022-01-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписчика', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
